
#ifndef DEFINES

#define DATASET_SIZE    100000
#define CLUSTER_SIZE    100
#define THRESHOLD       1e-50
#define PERCENTAGE		0.95

#define WRAPDIM 256
#define WRAPDIM_C 32

#define BLOCKDIM_C (CLUSTER_SIZE+WRAPDIM_C-1)/WRAPDIM_C
#define BLOCKDIM (DATASET_SIZE+WRAPDIM-1)/WRAPDIM


#define DEFINES
#endif // !DEFINES