
#ifndef DEFINES

#define DATASET_SIZE    100000
#define CLUSTER_SIZE    16
#define THRESHOLD       1e-10
#define PERCENTAGE		1

#define BLOCK 256
#define BLOCK_C 32

#define GRID_C (CLUSTER_SIZE+BLOCK_C-1)/BLOCK_C
#define BLOCKDIM (DATASET_SIZE+BLOCK-1)/BLOCK

#define NUM_CLUSTER PERCENTAGE*CLUSTER_SIZE

#define DEFINES
#endif // !DEFINES


