
#ifndef DEFINES

#define DATASET_SIZE    100000
#define CLUSTER_SIZE    16
#define THRESHOLD       1e-10
#define PERCENTAGE		1

#define WRAPDIM 128
#define WRAPDIM_C 32

#define BLOCKDIM_C (CLUSTER_SIZE+WRAPDIM_C-1)/WRAPDIM_C
#define BLOCKDIM (DATASET_SIZE+WRAPDIM-1)/WRAPDIM

#define NUM_CLUSTER PERCENTAGE*CLUSTER_SIZE


#define DEFINES
#endif // !DEFINES


